// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Emoji: typeof import('./src/components/Emoji/index.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor/index.vue')['default']
    NoData: typeof import('./src/components/NoData/index.vue')['default']
    PageLoading: typeof import('./src/components/PageLoading/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    ViewerImg: typeof import('./src/components/ViewerImg/index.vue')['default']
  }
}

export { }
