// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/ArticleCard/index.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList/index.vue')['default']
    Aside: typeof import('./src/components/Layout/Aside/index.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    CommentConent: typeof import('./src/components/Comment/components/CommentConent.vue')['default']
    CommentContent: typeof import('./src/components/Comment/components/CommentContent.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    Emoji: typeof import('./src/components/Emoji/index.vue')['default']
    Footer: typeof import('./src/components/Layout/Footer/index.vue')['default']
    Header: typeof import('./src/components/Layout/Header/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LinkTab: typeof import('./src/components/Layout/components/LinkTab.vue')['default']
    Main: typeof import('./src/components/Layout/Main/index.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor/index.vue')['default']
    NoData: typeof import('./src/components/NoData/index.vue')['default']
    PageLoading: typeof import('./src/components/PageLoading/index.vue')['default']
    Slider: typeof import('./src/components/Layout/Header/components/Slider.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    ViewerImg: typeof import('./src/components/ViewerImg/index.vue')['default']
    WebInfo: typeof import('./src/components/WebInfo/index.vue')['default']
  }
}

export { }
